# requires BuildKit
FROM golang:1.25-alpine3.23 AS builder

WORKDIR /build

ARG CGO_ENABLED=0

ARG GOCACHE=/root/.cache/go-build
ARG GOMODCACHE=/root/.cache/go-mod

RUN --mount=type=cache,target=/root/.cache/go-build \
  --mount=type=cache,target=/root/.cache/go-mod \
  --mount=type=bind,source=.,target=/build \
  go build -o /ws-server main.go


FROM scratch

COPY --from=builder /ws-server /usr/local/bin/wsserver

ENTRYPOINT [ "/usr/local/bin/wsserver" ]
