version: "2"

run:
  tests: true

linters:
  enable:
    - depguard
    - goconst
    - gocritic
    - gocyclo
    - prealloc
  disable:
    - funlen
  settings:
    depguard:
      rules:
        main:
          list-mode: lax
          allow:
            - github.com/gorilla/websocket
    gocyclo:
      min-complexity: 15

  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
        text: Close
    paths:
      - .*_gen.go
      - scripts
      - third_party$
      - builtin$
      - examples$

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - github.com/echoCTF/ws-server
  exclusions:
    generated: lax
    paths:
      - .*_gen.go
      - scripts
      - third_party$
      - builtin$
      - examples$
